Polkamarkets/polkamarkets-web

src/App.tsx
src/components/CreateMarketForm/CreateMarketFormFund.tsx
src/hooks/useNetwork/useNetwork.tsx
src/pages/CreateMarket/CreateMarket.tsx
src/pages/Home/Home.tsx
src/pages/Leaderboard/prepare.tsx

It is just some resolutions for debugger reports

[NO-STORY] Resolve debugger alerts

---

.github/pull_request_template.md

I'm leaving this starter template here for us to discuss. I'm fine if we follow along with that too.

[NO-STORY] Create pull_request_template.md

---

.github/pull_request_template.md

Some enhancements and typo.
_NO-STORY_
> `useHook`/`useHook()` is related to React JS hooks, located on `src/hooks/` path
> `Component`/`<Component />` is related to React JS components, located on `src/components/` path
> `[prop]`/`[prop=value]` is related to that prop components
What and why would be added, changed or removed after that pull request.
| _Unit_             | 🟢 Added        | 🟡 Changed | 🔴 Removed |
| ------------------ | --------------- | ---------- | ---------- |
| 🟡 Pull Request Template |  | Just adding some more information and fixing typo           |            |

[NO-STORY] Update pull_request_template.md

---

src/components/Feature/Feature.tsx
src/components/Feature/index.ts
src/components/WalletInfo/WalletInfo.tsx
src/components/WalletInfo/WalletInfoBuy.tsx
src/components/WalletInfo/WalletInfoClaim.tsx
src/components/index.ts
src/config/environment.ts
src/config/features.ts
src/config/index.ts
src/types/transaction.ts

| 🟢 `<Feature />` | Wraps features that was configured using env vars |  |  |
| 🟢  `config/features.ts` | Enumerates all on/off features |  |  |
| 🟢  `types/transaction.ts` | Creates `Transaction` type |  |  |
| 🟢  `<WalletInfoClaim />` | Adds claim, loading, transaction state and toast actions |  |  |
| 🟡  `config/environment.ts` |  | Adds `FEATURE_CLAIM` var |  |
> 
> 

[796] Add Loader/Toast to Claim Action

---

src/pages/Leaderboard/Leaderboard.tsx
src/pages/Leaderboard/LeaderboardYourStats.tsx
src/pages/Leaderboard/prepare.tsx
src/pages/Leaderboard/types.tsx

[809] IFL - Leaderboard tweaks

---

server/index.js
src/components/CreateLeaderboardGroup/CreateLeaderboardGroup.module.scss
src/components/CreateLeaderboardGroup/CreateLeaderboardGroup.tsx
src/components/CreateLeaderboardGroup/CreateLeaderboardGroup.util.ts
src/components/CreateLeaderboardGroup/index.ts
src/components/CreateLeaderboardGroupForm/CreateLeaderboardGroupForm.module.scss
src/components/CreateLeaderboardGroupForm/CreateLeaderboardGroupForm.tsx
src/components/CreateLeaderboardGroupForm/CreateLeaderboardGroupForm.type.ts
src/components/CreateLeaderboardGroupForm/CreateLeaderboardGroupForm.util.ts
src/components/CreateLeaderboardGroupForm/index.ts
src/components/Input/InputErrorMessage.tsx
src/components/Input/TextArea.tsx
src/components/Input/index.tsx
src/components/index.ts
src/pages/Leaderboard/Leaderboard.tsx
src/pages/Leaderboard/Leaderboard.util.ts
src/pages/Leaderboard/types.tsx
src/routes/app.routes.tsx
src/services/Polkamarkets/index.ts
src/services/Polkamarkets/types.ts
src/styles/pages/_leaderboard.scss
src/types/leaderboard.ts

[816] Group Leaderboards

---

src/components/Market/MarketFooterActions.tsx

[846] IFL - Change content of the "Share market" feature

---

src/components/Filter/Filter.tsx
src/styles/components/_filter.scss
src/styles/components/_table.scss

[849]  IFL - Mobile Tweaks

---

src/components/BetaWarning/BetaWarning.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Market/Market.tsx
src/styles/components/_beta-warning.scss
src/styles/components/_market-card.scss

Fix for related bugs.
1. Open the app;
2. Click upon the label or checkbox and the Beta Modal Warning shall close at first;
| 🟡`<Market />` |  | Wraps market avatar as a workaroung for zoomed image |  |
| 🟡`<BetaWarning />` |  | Moves links from the checkbox label to modal footer |  |
| - | - | - |
| `<Market />` | 🔴 | The workaround should be noticed and removed as soon as it's not necessary anymore | 
> 
> 
> `module()` is related to modules located on `src/utils/` or anywhere else on the app that …

[872] Bugs 12/06/2022

---

src/components/Input/ImageUploadInput.tsx
src/pages/Leaderboard/Leaderboard.tsx
src/styles/components/_input.scss
src/styles/pages/_leaderboard.scss

[908] Image Uploader Issues

---

src/components/Layout/Layout.tsx
src/pages/Profile/ProfileSummary.tsx
src/styles/layout/_layout.scss
src/styles/pages/_profile.scss

Adds Profile responsive UI.
https://user-images.githubusercontent.com/16447765/209242832-802e72e6-1fd0-441c-94ef-de24726277dd.mp4
| 🟡`<Layout />` |  | Move `Footer` outside its `Container` parent one  |  |
| 🟡`<ProfileSummary />` |  | Simplify component body  |  |
|  |  | Adjust _address_ and _stats_ responsive UI  |  |
> 
> 

[934] IFL - Fix Mobile

---

src/pages/Leaderboard/Leaderboard.util.ts

1. Do this;
2. Do that;
| - | - | - |
- …

fix(Leaderboard): case insensitive filter group leaderboards

---

src/components/ApproveToken/ApproveToken.tsx
src/components/LiquidityForm/LiquidityFormActions.tsx
src/styles/components/_liquidity-form.scss

1. Do this;
2. Do that;
| - | - | - |
> `useHook()` is related to React JS hooks, located …

V2 Final Tweaks

---

src/components/WalletInfo/WalletInfo.tsx
src/helpers/shortenAddress.test.ts
src/helpers/shortenAddress.ts

1. Do this;
2. Do that;
| - | - | - |
> 
> 

[1079] Show 2 more characters in user wallet

---

src/services/PolkamarketsService.ts

1. Do this;
2. Do that;
| - | - | - |
- …

fix(PolkamarketsService): async login issues

---

src/components/Market/Market.tsx
src/components/MarketAvatar/MarketAvatar.tsx
src/components/TradeForm/TradeFormPredictions.tsx
src/pages/Market/MarketHead.tsx
src/redux/ducks/ui.ts
src/ui/Avatar/Avatar.tsx
src/ui/Hero/Hero.module.scss
src/ui/Hero/Hero.tsx
src/ui/useAverageColor/useAverageColor.ts

https://user-images.githubusercontent.com/16447765/224125703-d73c0196-cfd3-4191-9117-cfa7807d4566.mp4
1. Do this;
2. Do that;
| - | - | - |
> 
> 
> `module()` is related to modules located on …

[1075] Hero bugs

---

src/components/Market/Market.module.scss
src/components/Market/MarketFooterStats.tsx

[1081] Market Info Hovers

---

src/components/LineChart/LineChart.tsx
src/components/LineChart/options.ts

[1095] Market Page - Refactor Date Label

---

src/contexts/filters/filters.util.ts
src/helpers/date.ts
src/pages/Home/Home.module.scss
src/pages/Home/HomeFilter.tsx
src/redux/ducks/markets.ts
src/ui/RangePicker/RangePicker.module.scss
src/ui/RangePicker/RangePicker.styles.ts
src/ui/RangePicker/RangePicker.tsx
src/ui/RangePicker/RangePicker.type.ts
src/ui/RangePicker/index.ts
src/ui/index.ts

[1096] V2 - Custom end date field

---

src/redux/ducks/markets.ts

[1129] Ignore markets with unknown networks

---

package.json
src/components/LiquidityForm/LiquidityFormActions.tsx
src/components/TradeForm/TradeFormActions.tsx
src/hooks/useERC20Balance/useERC20Balance.store.ts
src/hooks/useERC20Balance/useERC20Balance.ts
src/hooks/useERC20Balance/useERC20Balance.type.ts
src/hooks/useToastNotification.js
yarn.lock

[1117] Load market token balance after every transaction

---

src/pages/Portfolio/PortfolioAnalytics.tsx
src/pages/Portfolio/PortfolioChart.tsx
src/pages/Portfolio/PortfolioPage.tsx
src/pages/Portfolio/type.ts
src/styles/theme/_aliases.scss
src/styles/theme/_tokens.scss
src/ui/Skeleton/Skeleton.module.scss
src/ui/Skeleton/Skeleton.tsx
src/ui/Skeleton/index.ts
src/ui/index.ts

https://user-images.githubusercontent.com/16447765/232043875-4e75cd12-b0ae-4dea-80f9-c9d15469f5db.mov
1. Do this;
2. Do that;
| - | - | - |
> 
> 
> `module()` is related to modules located on …

[1131] Portfolio Page feedback

---

src/components/CreateLeaderboardGroupForm/CreateLeaderboardGroupForm.tsx
src/components/Layout/Layout.tsx
src/config/ui.ts
src/hooks/useNetwork/useNetwork.context.tsx
src/pages/Market/Market.tsx

[1175] Fantasy Feature Flag: Remove Disclaimer

---

src/components/Market/MarketFooterStats.tsx
src/pages/Market/MarketAnalytics.tsx

[1183] Fantasy Feature Flag: Market Info: Remove Data

---

src/pages/Profile/ProfileLeaderboardRanks.tsx
src/pages/Profile/ProfilePredictionStatistics.tsx

[1189] Fantasy Feature Flag: Remove Profile Page Info

---

src/contexts/filters/filters.context.tsx
src/contexts/filters/filters.type.ts
src/contexts/filters/filters.util.ts

[1186] Fantasy Feature Flag: Remove Filters

---

src/components/TradeForm/TradeForm.tsx
src/components/TradeForm/TradeFormDetails.tsx

[1204] Fantasy Feature Flag: Remove info from Trading Form

---

src/components/CreateMarketFormDetails/CreateMarketFormDetails.tsx
src/config/environment.ts
src/config/ui.ts
src/contexts/filters/filters.type.ts
src/contexts/filters/filters.util.ts
src/hooks/useMarkets.ts
src/pages/Home/Home.module.scss
src/pages/Home/HomeFilter.tsx
src/redux/ducks/markets.ts

[1209] V2 - Add Categories Back

---

src/components/CreateMarketFormFund/MarketPreview/MarketPreview.tsx

[1214] V2 - Add Network + Fee on Market Create Preview Footer

---

src/components/CreateMarketForm/CreateMarketForm.tsx

[1216] V2 - Update Wallet after Market Creation

---

src/pages/Market/Market.module.scss
src/pages/Market/Market.tsx
src/pages/Market/MarketAbout.tsx
src/styles/pages/_market.scss

1. Do this;
2. Do that;
| - | - | - |
> `useHook()` is related to React JS hooks, located …

[1212] V2 - Description not parsing paragraphs

---

src/components/MarketList/MarketList.tsx
src/pages/Achievements/Achievements.tsx
src/pages/Clubs/Clubs.tsx
src/pages/Home/Home.tsx
src/pages/Home/HomeFilter.tsx
src/pages/Leaderboard/Leaderboard.tsx
src/pages/Market/Market.tsx
src/pages/Market/MarketAbout.tsx
src/pages/Portfolio/PortfolioPage.tsx
src/pages/Profile/Profile.tsx
src/styles/components/_market-list.scss
src/styles/pages/_home.scss
src/styles/sizing/_max-width.scss
src/styles/sizing/index.scss

[1221] V2 - Layout in Container

---

src/assets/icons/svgs/v2-badge.svg
src/components/Header/HeaderNav.module.scss
src/components/Header/HeaderNav.tsx
src/pages/Clubs/Clubs.tsx

1. Do this;
2. Do that;
| - | - | - |
> 
> …

[1226] New Navbar/V2 Badge

---

src/config/environment.ts
src/config/ui.ts
src/pages/Leaderboard/Leaderboard.tsx
src/pages/Leaderboard/Leaderboard.util.ts
src/pages/Leaderboard/prepare.tsx
src/pages/Leaderboard/types.tsx

1. Do this;
2. Do that;
| - | - | - |
- …

fix(Leaderboard): net volume/liquidity columns

---

src/config/ui.ts
src/contexts/filters/filters.type.ts
src/contexts/filters/filters.util.ts
src/hooks/useMarkets.ts
src/redux/ducks/markets.ts

[1251] - ERC20 Tokens Filter

---

src/components/SelectTokenModal/SelectTokenModal.module.scss
src/components/SelectTokenModal/SelectTokenModal.tsx
src/config/environment.ts
src/config/ui.ts

[1266]  V2 - Block POLK from being used in market creation

---

src/components/SearchBar/SearchBar.tsx
src/components/SelectTokenModal/SelectTokenModal.tsx
src/pages/Home/Home.module.scss
src/pages/Home/Home.tsx
src/styles/components/_filter.scss
src/styles/components/_searchbar.scss

1. Do this;
2. Do that;
| - | - | - |
> 
> …

[1254] Home nav has inconsistent items height

---

src/components/ApproveToken/ApproveToken.tsx
src/components/ReportForm/ReportFormActions.tsx
src/components/Steps/Steps.tsx

[1281] Token Approval Button Show Criteria

---

src/components/CreateMarketForm/CreateMarketForm.tsx
src/components/CreateMarketForm/CreateMarketForm.type.ts
src/components/CreateMarketForm/CreateMarketForm.util.ts
src/components/CreateMarketFormDetails/CreateMarketFormDetails.tsx
src/models/market.ts
src/pages/Market/Market.tsx

1. Do this;
2. Do that;
| - | - | - |
- …

[1282] Display Resolution Source only when fantasy mode is disabled

---

src/components/ApproveToken/ApproveToken.tsx
src/components/LiquidityForm/LiquidityFormActions.tsx
src/components/ReportForm/ReportFormActions.tsx
src/components/TradeForm/TradeFormActions.tsx
src/components/VoteModal/VoteModal.tsx
src/pages/Achievements/Achievements.tsx
src/pages/Market/utils.tsx
src/pages/Profile/ProfileSummary.tsx

[1292] Fantasy - Hide Data

---

src/components/Layout/Layout.tsx
src/components/LiquidityForm/LiquidityFormActions.tsx
src/components/ReportForm/ReportFormActions.tsx
src/components/Trade/TradeActions.tsx
src/components/TradeForm/TradeFormActions.tsx
src/components/TradeForm/TradeFormInput.tsx
src/components/VoteModal/VoteModal.tsx

[1295] Social Login - Hide Data

---

src/assets/icons/pages/leaderboard/MyPlaceIcon.tsx
src/components/ReportForm/ReportFormActions.tsx
src/pages/Leaderboard/Leaderboard.util.ts
src/pages/Leaderboard/prepare.tsx
src/pages/Leaderboard/types.tsx
src/services/Polkamarkets/types.ts
src/styles/pages/_leaderboard.scss
src/ui/Avatar/Avatar.module.scss
src/ui/Avatar/Avatar.tsx

[1287] Leaderboard - Display username + image

---

src/pages/Leaderboard/Leaderboard.tsx
src/pages/Leaderboard/Leaderboard.util.ts
src/pages/Leaderboard/prepare.tsx
src/pages/Leaderboard/types.tsx
src/pages/Profile/ProfileLeaderboardRanks.tsx
src/pages/Profile/ProfilePredictionStatistics.tsx
src/pages/Profile/ProfileYourStats.tsx
src/pages/Profile/prepare.tsx
src/pages/Profile/types.tsx
src/services/Polkamarkets/types.ts

1. Do this;
2. Do that;
| - | - | - |
- …

feat(Leaderboard): add earnings column

---

src/components/Header/HeaderActions.module.scss
src/components/Header/HeaderActions.tsx
src/components/Logos/Logos.tsx
src/components/ProfileSignout/ProfileSignout.module.scss
src/components/ProfileSignout/ProfileSignout.tsx
src/pages/Leaderboard/prepare.tsx
src/pages/Profile/Profile.module.scss
src/pages/Profile/Profile.tsx
src/pages/Profile/ProfileError.tsx
src/pages/Profile/ProfileLeaderboardRanks.tsx
src/pages/Profile/ProfilePredictionStatistics.tsx
src/pages/Profile/ProfileSummary.tsx
src/pages/Profile/types.tsx
src/styles/components/_wallet-info.scss

[Fantasy - Show User data in Profile page](https://app.shortcut.com/polkamarkets/story/1300/fantasy-show-user-data-in-profile-page)

[1300] Fantasy - Show User data in Profile page

---

package.json
src/components/Market/MarketOutcomes.module.scss
src/components/Market/MarketOutcomes.tsx
src/components/ModalContent/ModalContent.module.scss
src/components/Trade/Trade.module.scss
src/components/Trade/Trade.tsx
src/components/Trade/TradePredictions.tsx
src/components/Trade/TradePredictionsWithImages.tsx
src/pages/Market/Market.module.scss
src/pages/Market/MarketPredictions.tsx
src/pages/Market/MarketShares.module.scss
src/pages/Market/MarketShares.tsx
src/styles/main.scss
src/styles/theme/_aliases.scss
src/styles/vendors/_react-horizontal-scrolling-menu.scss
yarn.lock

[1317] Fantasy - New Trading Experience w/Images

---

src/components/Footer/Footer.module.scss
src/components/Footer/Footer.tsx
src/components/Footer/Footer.type.ts
src/components/Footer/Footer.utils.ts
src/config/environment.ts
src/config/ui.ts

[1342] Fantasy - Dynamic Footer

---

src/components/ProfileSignout/ProfileSignout.tsx
src/components/WalletInfo/WalletInfoClaim.tsx
src/redux/ducks/polkamarkets.ts

[1432] Fantasy - Claiming Balance Loader

---

src/components/ProfileSignout/ProfileSignout.tsx

Remove discord condition

---

src/components/Profile/Profile.module.scss
src/components/Profile/Profile.tsx
src/components/ProfileSignin/ProfileSignin.module.scss
src/components/ProfileSignin/ProfileSignin.tsx
src/pages/Home/HomeHero.tsx

[1462] Ajustar CTA 'Saber mais' por login sob condição

---

src/redux/ducks/polkamarkets.ts
src/services/PolkamarketsService.ts

feat(redux): claim winnings if any pending

---

src/components/Footer/Footer.tsx
src/components/Header/HeaderActions.module.scss
src/components/Header/HeaderActions.tsx
src/components/Header/HeaderNav.module.scss
src/components/Header/HeaderNav.tsx
src/components/HelpButton/HelpButton.module.scss
src/components/HelpButton/HelpButton.tsx
src/components/HelpButton/index.ts
src/components/Market/MarketOutcomes.tsx
src/components/ProfileSignin/ProfileSignin.tsx
src/components/Trade/TradeActions.tsx
src/pages/Tournaments/TournamentsUpcomingMarkets.module.scss
src/redux/ducks/markets.ts

[ENG-155 ] Login Tweaks

---

src/components/CreateMarketForm/CreateMarketForm.util.ts
src/components/CreateMarketFormFund/CreateMarketFormFund.tsx
src/components/CreateMarketFormFund/MarketPreview/MarketPreview.tsx

Feat/eng 163/create market tweaks

---

src/components/Header/HeaderActions.tsx
src/components/Header/HeaderNav.module.scss
src/components/Header/HeaderNav.tsx
src/components/Modal/Modal.tsx
src/config/pages.ts
src/helpers/getPathname.test.ts
src/helpers/getPathname.ts

[ENG-155] Login Tweaks - burger-menu

---

src/components/TradeForm/TradeFormInput.tsx
src/pages/Home/HomeNav.tsx
src/pages/Market/Market.tsx
src/pages/Market/MarketShares.tsx
src/pages/Tournament/TournamentNav.tsx

Feat/eng 187/copy tweaks

---

src/components/ProfileSignout/ProfileSignout.tsx
src/pages/Leaderboard/Leaderboard.util.ts
src/pages/Leaderboard/prepare.tsx
src/pages/Leaderboard/types.tsx
src/pages/Market/MarketActivity.tsx
src/pages/Market/MarketComments.tsx
src/pages/Profile/types.tsx
src/pages/Tournament/TournamentTopUsers.utils.tsx
src/services/Polkamarkets/types.ts
src/types/market.ts

feat(User): slugify urls

---

src/components/Layout/Layout.module.scss
src/components/Layout/Layout.tsx
src/config/pages.ts
src/hooks/useMarketLand.ts
src/pages/Embed/Embed.module.scss
src/pages/Embed/Embed.tsx
src/pages/Embed/index.ts
src/routes/app.routes.tsx
src/styles/theme/_global.scss
src/ui/Spinner/Spinner.tsx

[ENG-217](https://linear.app/polkamarkets-labs/issue/ENG-217/market-widget)

[ENG-217] Market Widget

---

src/components/InfoTooltip/InfoTooltip.module.scss
src/components/InfoTooltip/InfoTooltip.tsx
src/components/InfoTooltip/index.ts
src/components/ProfileSignout/ProfileSignout.tsx
src/components/Tooltip/Tooltip.tsx
src/components/TradeForm/TradeFormInput.tsx
src/components/index.ts
src/components/new/TableMini/TableMini.tsx
src/pages/Profile/ProfilePredictionStatistics.tsx
src/styles/components/_amount-input.scss

[ENG-220](https://linear.app/polkamarkets-labs/issue/ENG-220/tooltips-to-include)

[ENG-220] Tooltips to include

---

src/components/Market/MarketFooterStats.tsx

fix(MarketFooterStats): add `toLocaleString` to `users` and `volume`

---

src/components/Trade/Trade.module.scss

[ENG-238](https://linear.app/polkamarkets-labs/issue/ENG-238/broken-single-prediction-ui)

[ENG-238] Broken single prediction UI

---

src/components/Trade/TradeActions.tsx
src/components/TradeForm/TradeFormActions.tsx
src/hooks/useReloadMarketPrices.ts
src/redux/ducks/market.ts

[ENG-240](https://linear.app/polkamarkets-labs/issue/ENG-240/trade-actions-affecting-different-markets)

[ENG-240] Trade actions affecting different markets

---

src/config/pages.ts
src/helpers/isError404.ts
src/pages/Error404/Error404.module.scss
src/pages/Error404/Error404.tsx
src/pages/Error404/index.ts
src/pages/Land/Land.tsx
src/pages/Market/MarketPredictions.tsx
src/pages/Profile/Profile.tsx
src/pages/Tournament/Tournament.tsx
src/pages/Tournament/TournamentTopUsers.tsx
src/routes/app.routes.tsx

[ENG-227] Improve 404 Page

---

src/services/PolkamarketsService.ts
yarn.lock

Feat/eng 156/update realitio methods
