Polkamarkets/polkamarkets-web

- src/pages/Market/Market.tsx
Currently, when clicking on the `Back to markets` action, the sidebar (and its respective form) remains with the selected market state, causing an inconsistency between the list of markets and the content of the sidebar.
This change will clear the sidebar state before returning to the markets page.
| 🟡 Market | | Resets sidebar state in `Back to markets` action  | |
> 
> 
> [678] Trading Bar is not closed when clicking on Back to Markets in market page

- src/pages/Portfolio/PortfolioPage.tsx
- src/pages/Portfolio/PortfolioTabs.tsx
- src/pages/Portfolio/utils.ts
- src/redux/ducks/polkamarkets.ts
- src/services/Polkamarkets/index.ts
- src/services/PolkamarketsService.ts
- yarn.lock
Currently, the portfolio page perform several api calls to fetch all markets from all states (`open`, `closed` and `resolved`) to build table rows.
This will make it possible to select only the markets that have some action and use them as parameters for a more efficient `getMarkets` request.
| 🟡  polkamarkets-js || Upgraded to latest version ||
| 🟡  useGetMarketsByIdsQuery || Adds network_id query param ||
| 🟡  PolkamarketsService || Adds getBondMarketIds method ||
| 🟡  PolkamarketsSlice || Adds initialState type ||
||| Adds marketsWithActions derivated from actions ||
||| Adds marketsWithBonds derivated from questionId ||
||| Creates bonds and actions loading state ||
| 🟡  PortfolioPage || Removes getMarkets api calls ||
| …
> [681] Portfolio - Request Markets from Portfolio Market IDs

- package.json
- src/components/Footer/Footer.tsx
- src/components/Footer/FooterTerms.tsx
- src/components/Layout/Layout.tsx
- src/components/Market/MarketOutcomes.tsx
- src/components/MarketList/MarketListAsync.tsx
- src/components/PredictionCard/PredictionCard.tsx
- src/components/VirtualizedList/VirtualizedList.tsx
- src/components/VirtualizedList/index.tsx
- src/components/index.tsx
- src/components/plots/Area/Area.tsx
- src/components/plots/Area/Area.type.ts
- src/components/plots/Area/Area.util.ts
- src/components/plots/Area/index.tsx
- src/components/plots/index.tsx
- src/hooks/index.ts
- src/hooks/useFooterVisibility/index.ts
- src/hooks/useFooterVisibility/useFooterVisibility.tsx
- src/hooks/useFooterVisibility/useFooterVisibility.type.ts
- src/pages/Home/Home.tsx
- src/pages/Home/HomeCategories.tsx
- src/pages/Home/HomeMobileInfo.tsx
- src/styles/abstracts/variables/components/_market-list.scss
- src/styles/components/_market-list.scss
- src/styles/components/_tabs.scss
- src/styles/layout/_layout.scss
- src/styles/pages/_home.scss
- src/styles/pages/_market.scss
- yarn.lock
Rendering performance improvements in the market list and outcome charts.
Charts that were previously built on top of the `apexcharts` library were rewritten using the `recharts` library.
Market list is [virtualized](https://www.patterns.dev/posts/virtual-lists/) using the `react-virtuoso` library.
1. [https://www.patterns.dev/posts/virtual-lists/](https://www.patterns.dev/posts/virtual-lists/)
| 🟢 Area | Area chart using `recharts` library | | |
| 🟢 VirtualizedList | Virtualized list using `react-virtuoso` library | | |
| 🟢 useFooterVisibility | Stores `footer` visibility and export `show` / `hide` callbacks | | |
| 🟡 react-virtuoso | | Upgraded from `v2.13.2` to `v2.18.2` | |
| 🟡 MarketOucomes | | Replaces deprecated …
> [677] Market List - Apply React Virtuoso

- src/assets/icons/TWarningIcon.tsx
- src/components/ProgressBar/ProgressBar.tsx
- src/pages/CreateMarket/CreateMarketBuyPolk.tsx
There is a minimum amount of `POLK` to create a market.
The progress (displayed in the interface) of the amount may appear with a higher number of decimal places than expected.
This will limit you to a maximum of `2` decimal places.
| 🟡 TWarningIcon |  | Removes `fill` default value |  |
| 🟡 ProgressBar |  | Rounds current progress to 2 decimal numbers |  |
> 
> 
> [709] Round to 2 Decimal Numbers in Create Market POLK Modal

- package.json
- server/index.js
- yarn.lock
`X-Frame-Options ALLOW-FROM` https://app.polkamarkets.com/ not supported by several browsers, this caused Clickjacking on your domain/subdomain.
Attackers may have tricked the user, sending them malicious links, then the user opened it, clicked some image and their account unconsciously has been deactivated.
The vulnerability will be fixed by adding `X-Frame-Options DENY` to the security header.
1. [Helmet](https://helmetjs.github.io/);
1. Run `yarn build`
2. Run `yarn server`
1. Create a new HTML file anywhere
2. Put `<iframe src="http://localhost:5000/” frameborder="0"></iframe>`
3. Save the file in *.html format
4. Open that file in your browser
| 🟢 `helmet` | Provides a set of tools to configure HTTP headers |  |  |
| 🟡 …
> [741] Security - iframe Injection

- src/components/Market/MarketOutcomes.tsx
| 🟡 `<MarketsOutcomes />` | | Converts outcome title to kebab case before use as `Area` id |  |
> 
> 
> [801] Area charts with weird gradient background

- src/contexts/filters/filters.util.ts
- src/pages/Home/HomeNav.tsx
- src/redux/ducks/markets.ts
- Sort markets by "Expiration Date ASC" instead of our custom sorting algo
- By default, filter markets by "Open" and "Closed" state
> [808] IFL - Change default sorting and filters in Markets list

- src/components/AmountInput/AmountInput.tsx
- src/components/LiquidityForm/LiquidityFormInput.tsx
> [1116] `.` divider not working on liquidity/create market form

- src/ui/useTheme/useTheme.tsx
- src/ui/useUpdateEffect/useUpdateEffect.ts
1. Do this;
2. Do that;
| - | - | - |
> `useHook()` is related to React JS hooks, located …
> [no-story] Hook Adjustments

- src/components/Badge/Badge.tsx
- src/styles/base/_global.scss
- src/styles/components/_badge.scss
1. Do this;
2. Do that;
| - | - | - |
> `useHook()` is related to React JS hooks, located …
> [1151] My Positions Table - Wrong Alignment on Outcome Tags

- src/components/integrations/Transak/Transak.tsx
After transak operations, the document element still has `overflow: hidden` on its styles. This PR fixes it.
1. Open `Buy $ETH` or any operation which uses transak api;
2. After close it, inspect the document element node for having any styles;
|🟡`<Transak />`|  |Remove document element after transak operations |  |
> 
> 
> `module()` is related to modules located on `src/utils/` or anywhere …
> [NO-STORY] Allow page overflow after transak closes

- src/components/ProfileSigninEmail/ProfileSigninEmail.module.scss
> [1423] Fantasy - Email login with wrong font color in dark mode

- src/components/CreateMarketForm/CreateMarketForm.tsx
- src/components/CreateMarketForm/CreateMarketForm.util.ts
- src/components/CreateMarketFormDetails/CreateMarketFormDetails.tsx
- src/components/ImageCropper/ImageCropper.tsx
- src/components/Steps/Steps.tsx
- src/config/ui.ts
- src/contexts/filters/filters.util.ts
> [1440] Fantasy - Optional Market Image (Logic)

- src/components/CreateMarketFormFund/MarketPreview/MarketPreview.tsx
- src/components/Market/Market.tsx
- src/components/MarketAvatar/MarketAvatar.tsx
- src/components/PortfolioMarketTable/PortfolioMarketTable.module.scss
- src/components/PortfolioMarketTable/PortfolioMarketTable.tsx
- src/components/Trade/TradePredictions.tsx
- src/helpers/buildMarketColors.ts
- src/models/market.ts
- src/pages/Leaderboard/Leaderboard.tsx
- src/pages/Leaderboard/LeaderboardMarkets.tsx
- src/pages/Market/MarketHead.tsx
- src/pages/Market/MarketShares.tsx
- src/pages/Tournaments/TournamentsList.module.scss
- src/pages/Tournaments/TournamentsList.tsx
- src/redux/ducks/market.ts
- src/styles/pages/_leaderboard.scss
- src/ui/getAverageColor/getAverageColor.ts
> [1433] Fantasy - Optional Market Image (Style)

- src/components/Header/HeaderActions.tsx
- src/ui/useTheme/useTheme.tsx
> [1459] Fantasy - disable theme switcher

- src/components/ModalContent/ModalContent.module.scss
- src/components/Trade/Trade.tsx
> feat(Trade): only allow buying 1 outcome

- src/components/Trade/Trade.module.scss
- src/components/Trade/TradePredictionsWithImages.tsx
> [1468] Hide trade carrossel buttons with 2 outcomes

- src/components/LineChart/options.ts
- src/pages/Market/MarketChart.tsx
> feat(MarketChart): display probabilities on fantasy mode

- src/components/MarketList/MarketList.tsx
- src/components/Trade/TradePredictions.tsx
- src/pages/Market/Market.module.scss
> [ENG-183] “Show More” in multiple outcomes is not useful

- src/components/TradeForm/TradeFormInput.tsx
- src/styles/components/_amount-input.scss
[ENG-212](https://linear.app/polkamarkets-labs/issue/ENG-212/keep-the-suggested-prediction-option-visible-once-selected)
> [ENG-212] Keep the suggested prediction option visible once selected

- src/pages/Market/MarketShares.module.scss
- src/pages/Market/MarketShares.tsx
[ENG-230](https://linear.app/polkamarkets-labs/issue/ENG-230/unwrap-text-on-prediction-status-mobile)
> [ENG-230] Unwrap text on prediction status (mobile)

- src/components/Trade/TradePredictions.tsx
- src/components/Trade/TradePredictionsWithImages.tsx
- src/helpers/sortOutcomes.ts
- src/hooks/useExpandableOutcomes/useExpandableOutcomes.ts
[ENG-205](https://linear.app/polkamarkets-labs/issue/ENG-205/outcome-in-market-trade-modal-is-showing-wrong-colors)
> [ENG-205] Outcome in market trade modal is showing wrong colors

- src/styles/components/_prediction-card.scss
[ENG-253](https://linear.app/polkamarkets-labs/issue/ENG-253/adicionar-padding-nos-cards-a-direita)
> [ENG-253] Adicionar padding nos cards a direita

- src/pages/Market/Market.module.scss
- src/pages/Market/MarketChart.tsx
- src/pages/Market/MarketPredictions.tsx
- src/styles/components/_market.scss
[ENG-221](https://linear.app/polkamarkets-labs/issue/ENG-221/tornar-claro-o-conceito-de-probabilidade-no-previsometro) 
> [ENG-221] Tornar claro o conceito de Probabilidade no Previsómetro
